### ISSUE TITLE
添加 工作台 样式的 library

### ISSUE THREAD

**Issue by fahchen** [GreenNerd/cms_components#5]
https://tower.im/projects/81085f1a8d734769b56b62e22f49d583/

**Comment by Leecason** [comment]
没权限呀，进不去

**Comment by fahchen** [comment]
这个还在标注，标注完了给你哈

**Comment by fahchen** [comment]
![_pxcook](https://cloud.githubusercontent.com/assets/855678/20554664/659719ee-b198-11e6-8658-ea71ab54622e.png)
